// Acquire VS Code API
const vscode = acquireVsCodeApi();

// Get data injected from the extension
const lyric = window.posterData.lyric;
const bgSrc = window.posterData.bgSrc;

const canvas = document.getElementById('posterCanvas');
const ctx = canvas.getContext('2d');

// --- Drawing Logic ---

function draw() {
    // 1. Background (Gradient)
    const gradient = ctx.createLinearGradient(0, 0, 0, 800);
    gradient.addColorStop(0, '#1a1a1a');
    gradient.addColorStop(1, '#2d2d2d');
    ctx.fillStyle = gradient;
    ctx.fillRect(0, 0, 600, 800);

    // 2. Background Image (Circle Clip or Full)
    const img = new Image();
    img.src = bgSrc;
    img.onload = () => {
        // Draw image in the center with low opacity
        ctx.save();
        ctx.globalAlpha = 0.2;
        // Draw cover style
        ctx.drawImage(img, 100, 200, 400, 400); 
        ctx.restore();
        
        drawText();
    };
    img.onerror = () => {
        // If image fails, just draw text
        drawText();
    }
}

function drawText() {
    ctx.fillStyle = '#ffffff';
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';

    // 3. Lyric Text
    ctx.font = 'bold 32px "Microsoft YaHei", sans-serif';
    
    // Wrap text logic
    wrapText(ctx, lyric.content, 300, 350, 400, 50);

    // 4. Song Info
    ctx.fillStyle = '#aaaaaa';
    ctx.font = '20px sans-serif';
    ctx.fillText('—— ' + lyric.song + ' ——', 300, 600);
    ctx.font = '16px sans-serif';
    ctx.fillText('Album: ' + lyric.album, 300, 630);

    // 5. Footer
    ctx.fillStyle = '#FFD700';
    ctx.font = 'italic 14px sans-serif';
    ctx.fillText('Generated by Eason Code VSCode Extension', 300, 750);
}

function wrapText(context, text, x, y, maxWidth, lineHeight) {
    // Simple split by comma or spaces if too long
    const chars = text.split('');
    let line = '';
    let currentY = y;

    // Auto-split logic for long lines
    for(let n = 0; n < chars.length; n++) {
        const testLine = line + chars[n];
        const metrics = context.measureText(testLine);
        const testWidth = metrics.width;
        if (testWidth > maxWidth && n > 0) {
            context.fillText(line, x, currentY);
            line = chars[n];
            currentY += lineHeight;
        } else {
            line = testLine;
        }
    }
    context.fillText(line, x, currentY);
}

// --- Initialization ---

// Initial Draw
draw();

// Save Action
document.getElementById('saveBtn').addEventListener('click', () => {
    const dataUrl = canvas.toDataURL('image/png');
    vscode.postMessage({
        command: 'savePoster',
        data: dataUrl
    });
});
