// Acquire VS Code API
const vscode = acquireVsCodeApi();

// Get data injected from the extension
const lyric = window.posterData.lyric;
const bgSrc = window.posterData.bgSrc;

const canvas = document.getElementById('posterCanvas');
const ctx = canvas.getContext('2d');

// --- Drawing Logic ---

function draw() {
    // 1. Background Fill (Fallback)
    ctx.fillStyle = '#2d2d2d';
    ctx.fillRect(0, 0, canvas.width, canvas.height);

    // 2. Background Image (Full Screen Cover)
    const img = new Image();
    img.src = bgSrc;
    img.onload = () => {
        drawCoverImage(ctx, img);
        drawOverlay();
        drawText();
    };
    img.onerror = () => {
        // If image fails, just draw overlay and text
        drawOverlay();
        drawText();
    }
}

function drawCoverImage(ctx, img) {
    const canvasRatio = canvas.width / canvas.height;
    const imgRatio = img.width / img.height;
    let renderW, renderH, renderX, renderY;

    if (imgRatio > canvasRatio) {
        // Image is wider than canvas: Match height, center width
        renderH = canvas.height;
        renderW = img.width * (canvas.height / img.height);
        renderX = (canvas.width - renderW) / 2;
        renderY = 0;
    } else {
        // Image is taller than canvas: Match width, center height
        renderW = canvas.width;
        renderH = img.height * (canvas.width / img.width);
        renderX = 0;
        renderY = (canvas.height - renderH) / 2;
    }
    
    ctx.drawImage(img, renderX, renderY, renderW, renderH);
}

function drawOverlay() {
    // 3. Dark Overlay for Text Readability
    ctx.fillStyle = 'rgba(0, 0, 0, 0.6)'; // 60% opacity black
    ctx.fillRect(0, 0, canvas.width, canvas.height);
}

function drawText() {
    ctx.fillStyle = '#ffffff';
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';

    // 4. Lyric Text
    ctx.font = 'bold 36px "Microsoft YaHei", sans-serif';
    
    // Wrap text logic
    // Lift text slightly up
    wrapText(ctx, lyric.content, 300, 320, 450, 60);

    // 5. Song Info
    ctx.fillStyle = '#dddddd';
    ctx.font = '22px sans-serif';
    ctx.fillText('—— ' + lyric.song + ' ——', 300, 580);
    ctx.font = '16px sans-serif';
    ctx.fillText('Album: ' + lyric.album, 300, 615);

    // 6. Footer
    ctx.fillStyle = '#FFD700'; // Gold color
    ctx.font = 'italic 14px sans-serif';
    ctx.fillText('Generated by Eason Code VSCode Extension', 300, 750);
}

function wrapText(context, text, x, y, maxWidth, lineHeight) {
    const chars = text.split('');
    let line = '';
    let currentY = y;

    // Auto-split logic
    for(let n = 0; n < chars.length; n++) {
        const testLine = line + chars[n];
        const metrics = context.measureText(testLine);
        const testWidth = metrics.width;
        if (testWidth > maxWidth && n > 0) {
            context.fillText(line, x, currentY);
            line = chars[n];
            currentY += lineHeight;
        } else {
            line = testLine;
        }
    }
    context.fillText(line, x, currentY);
}

// --- Initialization ---

// Initial Draw
draw();

// Save Action
document.getElementById('saveBtn').addEventListener('click', () => {
    const dataUrl = canvas.toDataURL('image/png');
    vscode.postMessage({
        command: 'savePoster',
        data: dataUrl
    });
});
