import { Mood } from './types';

export const MOOD_LABELS: Record<Mood, string> = {
    'random': '🎲 随机漫步 (Random)',
    'sad': '🌧️ 深夜抑郁 (Sad)',
    'healing': '☕ 治愈哲理 (Healing)',
    'love': '💗 爱与浪漫 (Love)',
    'philosophy': '🤔 人生哲理 (Philosophy)',
    'life': '🌱 生活感悟 (Life)',
    'classic': '📀 岁月金曲 (Classic)',
    'memory': '🎞️ 往事回忆 (Memory)',
    'power': '💪 给人力量 (Power)',
    'crazy': '🔥 浮夸热血 (Crazy)',
    'lonely': '🍂 孤独患者 (Lonely)',
    'regret': '🥀 遗憾惋惜 (Regret)',
    'social': '🏙️ 社会观察 (Social)',
    'dark': '🌑 黑色幽默 (Dark)',
    'brightness': '☀️ 寻找光明 (Brightness)',
    'pain': '💔 痛彻心扉 (Pain)',
    'story': '📖 故事人生 (Story)',
    'friendship': '🤝 最佳损友 (Friendship)',
    'freedom': '🕊️ 向往自由 (Freedom)',
    'self': '🧘 自我对话 (Self)',
    'journey': '🚀 漫长旅途 (Journey)',
    'humanity': '👥 人性探索 (Humanity)',
    'soul': '👻 灵魂深处 (Soul)',
    'confused': '😵 迷茫困惑 (Confused)',
    'pressure': '🏋️ 压力释放 (Pressure)',
    'money': '💰 现实主义 (Money)',
    'promise': '🤞 爱的承诺 (Promise)',
    'acting': '🎭 人生如戏 (Acting)',
    'religion': '🙏 因果轮回 (Religion)',
    'repeat': '🔁 循环往复 (Repeat)'
};
